### ISSUE TITLE
0.0.9 release crashing

### ISSUE THREAD

**Issue by griffey** [MeasureTheFuture/mothership#11]
I believe the Mothership is crashing in 0.0.9. Started testing, after about 15 minutes or so the web interface stops responding, website doesn't load. On reboot and re-start of scout, system picks up where it was but crashes again in same timeframe. 

Logs attached. 

[scout.txt](https://github.com/MeasureTheFuture/mothership/files/474781/scout.txt)
[mothership.txt](https://github.com/MeasureTheFuture/mothership/files/474782/mothership.txt)

**Comment by cfreeman** [comment]
Sorry, was in a rush to try and get the scout fix to you late last night and didn't get a chance to test it properly. Won't get a chance to rebuild everything for a couple of days.

**Comment by cfreeman** [comment]
Ugh, I think I just managed to mess up the 0.0.9 build with some half finished stuff I was also working on at the same time as duration testing the scout. Multi-tasking fail. Did a completely fresh install for 0.0.10 (flashed Edison and started from scratch), been running for 35-45 minutes now no issues. 0.0.10 includes a database tweak (drops the created_at field from the scout_interactions table), so you will need to install from scratch.

This is fixed in v0.0.10, which is now available via https://github.com/MeasureTheFuture/installer

Please test and re-open this issue if the problem persists.

**Comment by griffey** [comment]
I will install the .10 and give it a long-running test this morning ASAP.
Feedback as soon as I can wrangle that and let it run for a few hours.
